/**
 * ラウンドの状態
 */
const ROUND_STATUS = {
	READY	: "READY",						//準備中
	RUNNING	: "RUNNING",					//実行中
	FINISH	: "FINISH"						//完了
}

/**
 * 各ラウンドで使う単語データ
 */
const ROUND_DATA = [
	{	// ラウンド１：最初の月のデータ
		limitSec: 60,
		aggregateCount: 15,
		roundName: '最初の月',
		words:[
			{ typing: "やたいでり", view: "屋台Deli" },
			{ typing: "あまんじゃく", view: "あまんじゃく" },
			{ typing: "ごめんや", view: "ごめんや" },
			{ typing: "とんとん", view: "とんとん" },
			{ typing: "きぶん", view: "紀文" },
			{ typing: "あらぶっふしゅん", view: "アラブッフ・シュン" },
			{ typing: "ばらのき", view: "薔薇の木" },
			{ typing: "ぐじぇーる", view: "グジェール" },
			{ typing: "やきとりのたく", view: "やきとりの拓" },
			{ typing: "とがし", view: "冨がし" },
			{ typing: "ばーがーずにゅーよーく", view: "バーガーズニューヨーク" },
			{ typing: "すぱいしーどらごん", view: "スパイシードラゴン" },
			{ typing: "とーだ", view: "トーダ" },
			{ typing: "りゅうかいかく", view: "龍海閣" },
			{ typing: "ぼんぐり", view: "ぼんぐ里" },
			{ typing: "らさこん", view: "ラ・サコン" },
			{ typing: "つるかめ", view: "ツルカメ" },
			{ typing: "えべれすときっちん", view: "エベレストキッチン" },
			{ typing: "すぱいすぷらざ", view: "スパイスプラザ" },
			{ typing: "むすかん", view: "ムスカン" },
			{ typing: "あんらくてい", view: "安楽亭" },
			{ typing: "うみふく", view: "海福" },
			{ typing: "さくら", view: "櫻" },
			{ typing: "きっちんあい", view: "キッチンアイ" },
			{ typing: "でんせつのちゅうかりょうりにん", view: "伝説の中華料理人" },
			{ typing: "うえんでぃーず", view: "ウエンディーズ" },
			{ typing: "さぼてん", view: "さぼてん" },
			{ typing: "ちゃぷちゃぷ", view: "チャプチャプ" }
		]
	},
	{	// ラウンド２：中の月のデータ
		limitSec: 60,
		aggregateCount: 15,
		roundName: '中の月',
		words: [
			{ typing: "わじょうりょうしゅ", view: "和醸良酒" },
			{ typing: "ひかりや", view: "光家" },
			{ typing: "ひまわり", view: "ひまわり" },
			{ typing: "すかいらぶ", view: "スカイラブ" },
			{ typing: "ごりあて", view: "ゴリアテ" },
			{ typing: "さくらのごとく", view: "桜の如く" },
			{ typing: "こころ", view: "こころ" },
			{ typing: "てんのうしゅか", view: "天王酒家" },
			{ typing: "らっしゅ", view: "ラッシュ" },
			{ typing: "あめりかーの", view: "アメリカーノ" },
			{ typing: "さいぜりや", view: "サイゼリヤ" },
			{ typing: "おおとや", view: "大戸屋" },
			{ typing: "いせや", view: "伊勢屋" },
			{ typing: "あーろんぽーと", view: "アーロンポート" },
			{ typing: "じゅけいろう", view: "聚慶楼" },
			{ typing: "ほどがやせんなりずし", view: "ほどがや千成鮨" },
			{ typing: "おらがそば", view: "おらが蕎麦" },
			{ typing: "もんてふぁーれ", view: "モンテファーレ" },
			{ typing: "いずあん", view: "伊豆庵" },
			{ typing: "きわみや", view: "極味家" },
			{ typing: "とりぶぎょう", view: "鶏奉行" },
			{ typing: "ほうらくえん", view: "宝楽園" },
			{ typing: "えどすし", view: "江戸寿司" },
			{ typing: "うしだる", view: "牛樽" },
			{ typing: "どうじょう", view: "道場" },
			{ typing: "まとあたり", view: "まとあたり" },
			{ typing: "ここいちばんや", view: "CoCo壱番屋" },
			{ typing: "くうかい", view: "空海" },
			{ typing: "しゃんはいはんてん", view: "上海飯店" }
		]
	},
	{	// ラウンド３：最後の月のデータ
		limitSec: 60,
		aggregateCount: 15,
		roundName: '最後の月',
		words: [
			{ typing: "せいふくえん", view: "盛福園" },
			{ typing: "うなへい", view: "うな平" },
			{ typing: "かげつ", view: "花月" },
			{ typing: "きたみ", view: "きたみ" },
			{ typing: "いちりん", view: "いちりん" },
			{ typing: "たつのき", view: "樹" },
			{ typing: "むらたや", view: "村田屋" },
			{ typing: "はっちん", view: "八珍" },
			{ typing: "ふらごーら", view: "フラゴーラ" },
			{ typing: "ちょわよ", view: "チョワヨ" },
			{ typing: "せいれん", view: "青蓮" },
			{ typing: "げん", view: "玄" },
			{ typing: "むぎまる", view: "麦まる" },
			{ typing: "とりいちもんじ", view: "とりいちもんじ" },
			{ typing: "まるふくさかば", view: "○福酒場" },
			{ typing: "まはろは", view: "マハロハ" },
			{ typing: "ほどがや", view: "ほどが家" },
			{ typing: "ひだかや", view: "日高家" },
			{ typing: "いっぴんえん", view: "一品苑" },
			{ typing: "ぶるどっく", view: "ブルドック" },
			{ typing: "うおひろ", view: "魚ひろ" },
			{ typing: "けんめり", view: "けんめり" },
			{ typing: "なかい", view: "なか井" },
			{ typing: "くしまる", view: "串まる" },
			{ typing: "ほどがやさかば", view: "ほどがや酒場" },
			{ typing: "うさぎのいるしま", view: "うさぎのいる島" },
			{ typing: "さかなやどうじょう", view: "さかなや道場" },
			{ typing: "てんのくら", view: "天の蔵" },
			{ typing: "ふくまる", view: "福○" },
			{ typing: "ぱたぱた", view: "パタパタ" },
			{ typing: "えいか", view: "栄華" },
			{ typing: "ふなちゅう", view: "鮒忠" },
			{ typing: "いえてい", view: "家帝" },
			{ typing: "ちくりん", view: "竹林" },
			{ typing: "てんてんぼう", view: "天天房" }
		]
	},
	{	// 最終ラウンド：早打ち王決定戦
		limitSec: 120,
		aggregateCount: 15,
		roundName: '早打ち王決定戦',
		words: [
			{ typing: "あじのもと", view: "味の素" },
			{ typing: "くのーるかっぷすーぷ", view: "クノールカップスープ" },
			{ typing: "やさしお", view: "やさしお" },
			{ typing: "ほんだし", view: "ほんだし" },
			{ typing: "なべきゅーぶ", view: "鍋キューブ" },
			{ typing: "なかむらたくじ", view: "中村 卓司" },
			{ typing: "はいみー", view: "ハイミー" },
			{ typing: "ぴゅあせれくとまよねーず", view: "ピュアセレクトマヨネーズ" },
			{ typing: "あみのばいたる", view: "アミノバイタル" },
			{ typing: "なかむらとおる", view: "中村 徹" },
			{ typing: "あくあそりた", view: "アクアソリタ" },
			{ typing: "おにくやわらかのもと", view: "お肉やわらかの素" },
			{ typing: "すーぷでり", view: "スープDELI" },
			{ typing: "やまだこうじ", view: "山田 浩二" },
			{ typing: "ぱるすいーと", view: "パルスイート" },
			{ typing: "まるどりがらすーぷ", view: "丸鶏がらスープ" },
			{ typing: "こうみぺーすと", view: "香味ペースト" },
			{ typing: "さいとうようた", view: "斉藤 洋太" },
			{ typing: "あじしお", view: "アジシオ" },
			{ typing: "おかずごはん", view: "おかずごはん" },
			{ typing: "きょうのおおざら", view: "きょうの大皿" },
			{ typing: "さらりあ", view: "サラリア" },
			{ typing: "やまざきまさつぐ", view: "山崎 正継" },
			{ typing: "めでぃみる", view: "メディミル" },
			{ typing: "あみのえーる", view: "アミノエール" },
			{ typing: "こずえみちあき", view: "梢 倫明" },
			{ typing: "ちゅうかあじ", view: "中華あじ" },
			{ typing: "せとのほんじお", view: "瀬戸のほんじお" },
			{ typing: "びおりご", view: "ビオリゴ" },
			{ typing: "させなおき", view: "佐瀬 直樹" },
			{ typing: "たんぱくしつがしっかりとれるすーぷ", view: "たんぱく質がしっかり摂れるスープ" },
			{ typing: "こんそめちきん", view: "コンソメチキン" },
			{ typing: "まつおひでき", view: "松尾 秀城" },
			{ typing: "すーぱーおおむぎがゆとりとほたてのだしじたて", view: "スーパー大麦がゆ鶏とホタテのだし仕立て" },
			{ typing: "くのーるかっぷすーぷぷれみあむ", view: "クノールカップスーププレミアム" },
			{ typing: "きじまかずひさ", view: "木島 和久" },
			{ typing: "あみのぷろていんちょこれーとあじ", view: "アミノプロテインチョコレート味" },
			{ typing: "それいけ！あんぱんまんすーぷ", view: "それいけ！アンパンマンスープ" },
			{ typing: "つめたいぎゅうにゅうでつくるじゃがいものぽたーじゅ", view: "冷たい牛乳でつくるじゃがいものポタージュ" },
			{ typing: "のみかた", view: "ノ・ミカタ" },
			{ typing: "はらだたくみ", view: "原田 匠" },
			{ typing: "ふんわりかにたまのもと", view: "ふんわりかに玉の素" },
			{ typing: "ほしかいばしらすーぷ", view: "干し貝柱スープ" },
			{ typing: "おしおひかえめのほんだし", view: "お塩控えめの・ほんだし" },
			{ typing: "かんこくちげすーぷ", view: "韓国チゲスープ" },
			{ typing: "おいすたーそーす", view: "オイスターソース" }
		]
	}
];

